### ISSUE TITLE
Ability to evaluate all rules in series, without setting priorities

### ISSUE THREAD

**Issue by zentuit** [CacheControl/json-rules-engine#103]
I have the situation where successful rules are supposed to add/subtract/multiply/divide values to user defined variables.  For example, if Q1 answer === 1, add 1 to variable `A`, if Q2 answer === 1, add 2 to variable `A`, etc.  

so if the facts come in with 
Q1 = 1, Q2 = 1 , then `A` === 3
Q1 = 1, Q2 = 0, then `A` === 1

I have the onSuccess function use `almanac.factValue('A')` to get current value, then do the operator (which is passed in `params`) and write the updated value out using `addRuntimeFact('A', updatedValue)`

But it looks like the runtime fact `A` isn't set from the first success when the second success fires so the end value is wrong.

What/how do you keep a running total?

**Comment by CacheControl** [comment]
@zentuit I suspect the issue may be that by default, rules are being evaluated in parallel, so there can be no guarantees about order.  Have you looked into setting [rule priorities](https://github.com/CacheControl/json-rules-engine/blob/master/docs/rules.md#setpriorityinteger-priority--1) so Q1 runs before Q2?

**Comment by CacheControl** [comment]
@zentuit That sounds awkward indeed, unfortunately I'm not sure there's another option for you in the immediate term.

Long term we could add an option to run rules in series, rather than parallel.  The default of running in parallel is for performance reasons (we want things to be fast by default), however there are drawbacks as your use case demonstrates.

**Comment by CacheControl** [comment]
closing - issue has been open over 2 years and haven't any additional requests.
