### ISSUE TITLE
RuleEngine User Interface

### ISSUE THREAD

**Issue by ozanerturk** [CacheControl/json-rules-engine#105]
Hello, this might not be a real issue but I have struggled to imagine how should it be like if we want to offer a Rule Engine User Interface.

Rule engine is perfect, really. I love it. But on the other hand I have to offer a web page which users can create Rule (Or, And so on) and system convert it to the Rule.json as rule of json-rule-engine. 
For example lets assume we are trying to create a campaign and  campaign needs rules.
Campaign entity has a lot of property which are the facts of our 'Rule'. 
I started work on it and after I see this is so complex to design it. 

Do you offer any approach or example to handle this use-case. 
Thanks a lot.

**Comment by CacheControl** [comment]
@ozanerturk rules engine UIs are notoriously complicated!  Giving humans the tools to express boolean logic is a very difficult problem to solve from a UX perspective, to say nothing of the engineering effort to design and build.  A google search for `rules engine` will show you some of the approaches people have tried.  Because the rule-engine needs of most businesses are highly customized and tailored to a particular use case, there are very few opportunities for re-use.

One key advantage of json-rules-engine is that (as you point out) the logic is expressed in a machine readable json data structure, which can be parsed to generate a UI.

The challenge of creating a UI can often be as large (or larger) than the effort of rule evaluation; you're correct that rules engine UIs tend to be large projects, and in my view that's to be expected for this problem space.

**Comment by ozanerturk** [comment]
After your comment, I continued my work on this subject and I created an example for it. I am leaving the link here:  [ozanerturk/json-rules-engine-ui](https://github.com/ozanerturk/json-rules-engine-ui/) 
As you said it was really compulsive to working with such a dynamic structure. I hope it will help someone who try to manage rule definition ui.  Thanks a lot!
