### ISSUE TITLE
can not remove rule

### ISSUE THREAD

**Issue by hehejiuhuizhe** [CacheControl/json-rules-engine#120]
Hello,I'm looking for a rule engine written in js,and I find this project easy to use,and following is my problem using the engine.
I add a rule,then run the engine per 1 second.
After 3 seconds,I remove the rule.
However,I still got "hello-world!" per second.
I think there need to be a  remove rule test. 
I have a look at the source code,the problem can be solved by adding  this.prioritizedRules = null   to removeRule.

Here is my code
```javascript


let Engine = require('json-rules-engine').Engine
let Rule = require('json-rules-engine').Rule

let engine = new Engine()
let rule = new Rule({
  conditions: {
    all: [{
      fact: 'displayMessage',
      operator: 'equal',
      value: true
    }]
  },
  event: {
    type: 'message',
    params: {
      data: 'hello-world!'
    }
  }
})
engine.addRule(rule)
engine.addFact('displayMessage', true);
engine.on('success', (event, almanac, ruleResult) => {
  console.log(event.params.data)
})
setInterval(() => {
  engine
    .run()
}, 1000);
setTimeout(() => {
  console.log('remove');
  engine.removeRule(rule);
}, 3000)
```

**Comment by CacheControl** [comment]
@hehejiuhuizhe This is correct - if the engine is `run()` after 1 second, it makes sense that the `success` event would be fired, since the rule still exists in the engine.

If the values were reversed and the rule was removed after 1 second and the engine run at 3 seconds, in that case seeing the event fired would be unexpected.

Does that make sense?  Or am I misunderstanding and you're making a different point?

**Comment by hehejiuhuizhe** [comment]
I mean the event would be fired when I use engine.run().But I have removed the rule so that there is no rule in the engine.
I think the expected behaviour is that after I remove the rule,the event wouldn't be fired when the engine run.

**Comment by CacheControl** [comment]
@hehejiuhuizhe I think you may be missing the concept behind `setTimeout()`.  Here's the timeline of events based on the code you posted:

t=0: Engine is created and rule added
t=1000: Engine is run and event fired
t=3000: Rule is removed

**Comment by hehejiuhuizhe** [comment]
@CacheControl 
I use setInterval to run the engine and setTimeout to remove the rule.So the timeline  is :
t=0: Engine is created and rule added
t=1000: Engine is run and event fired
t=2000: Engine is run and event fired
t=3000: Rule is removed
t=3000: Engine is run and event fired
t=4000: Engine is run and event fired
t=5000: Engine is run and event fired
....
The problem is that after 3000ms,and event shouldn't be fired.

**Comment by ozanerturk** [comment]
I checked the scenario @hehejiuhuizhe seems rigth. I came across with same result. when I debugged the code I realize run method calls  `prioritizeRules()` and it returns directly `priotizedRules` object if the `priotizedRules` list is not empty. Despite removeRule()  does not clear the `priotizedRules` list. So even if you call `removeRule()`  , `run` method is first looking to `priotizedRules` list to do the job and because removeRule does not clear the list there is still available rule in priotizedRules list.

https://github.com/CacheControl/json-rules-engine/blob/5ac00eafdf84eb93def58a44008e96bf7bd81bf4/src/engine.js#L146

https://github.com/CacheControl/json-rules-engine/blob/5ac00eafdf84eb93def58a44008e96bf7bd81bf4/src/engine.js#L64 

Simply little cache mechanizm brokes it. The list has to be recreated after removeRule method called or force to create new one in prioritizeRules method.
@CacheControl if you think this is the reason I can implement the fix if we agree on an idea.

**Comment by CacheControl** [comment]
@ozanerturk thanks for checking into this, and the offer to implement a fix.

I agree with your assessment. I think a good fix would be to add a line for setting the `prioritizedRules` variable to null, similar to how addRule() does it:

https://github.com/CacheControl/json-rules-engine/blob/5ac00eafdf84eb93def58a44008e96bf7bd81bf4/src/engine.js#L56
