### ISSUE TITLE
in operator 

### ISSUE THREAD

**Issue by care4truth** [CacheControl/json-rules-engine#121]
var customRule = new Rule({
                conditions : {
                    all : [{
                        fact : 'fact1',
                        operator : 'in',
                        value : 'value1'
                    },{
                        fact : 'fact2',
                        operator : 'in',
                        value : ['value2','value3']
                    }]
                } ,
                event : {
                    type : 'type1',
                    params : {
                        result : 'break'
                    }
                }
            });

suppose , if send {
           "fact1" : "value1",
           "fact2" : ["value2","value3"]
}
it should return 'break' as per my understanding of documentation.
But it is not.Appreciate your help.

**Comment by CacheControl** [comment]
@care4truth The problem is with `fact2` - essentially you are requesting the engine to compare whether the _fact value_ `["value2","value3"]` exists **within** the _rule value_ `['value2','value3']`, which it does not.

It sounds like you are wanting to compare array equality, which luckily is supported via [custom operators](https://github.com/CacheControl/json-rules-engine/blob/1583cd6ff8deaa2028cbad295101aeab907be2a8/docs/engine.md#engineaddoperatorstring-operatorname-function-evaluatefuncfactvalue-jsonvalue). See [example](https://github.com/CacheControl/json-rules-engine/blob/fae43e646b58cb7454b307a20a47a27ac22ad43b/examples/06-custom-operators.js).  Essentially you want to implement a custom operator that compares the contents of 2 arrays, and if they are identical, return truthy.
