### ISSUE TITLE
simplify/remove object-hash, decrease bundle size

### ISSUE THREAD

**Issue by hartzis** [CacheControl/json-rules-engine#127]
💡 Just wanted to start a discussion about the possibilities of removing/changing what `object-hash` is used for?

~40% of the bundled size is from `object-hash` - https://bundlephobia.com/result?p=json-rules-engine@2.3.4

**Comment by CacheControl** [comment]
That package is used for memoizing results of fact evaluation, based on the parameters provided.  So if a fact is called twice with the same parameters, it will only be evaluated once.  Depending on the complexity of evaluating the fact, this can result in a considerable performance improvement.

At the time it was chosen, it was the only mature library of its kind on npm.  Since then, it appears there are a few new faces:  [hash-it](https://github.com/planttheidea/hash-it), and [node-object-hash](https://github.com/SkeLLLa/node-object-hash) came it in my searches, both of which are much smaller dependencies.  There may be others as well.

There's some test coverage of this feature, and object-hash is only used in one place, so I think this could easily be swapped out for a smaller library!
