### ISSUE TITLE
How to add multiple facts into engine?

### ISSUE THREAD

**Issue by manerohit388** [CacheControl/json-rules-engine#154]
Hi,

Is there any way to add multiple facts into engine. Something like creating an array of all the facts and then inserting that array into engine. If not then how to add multiple facts into engine ?

**Comment by MattCopenhaver** [comment]
@manerohit388 For adding facts to the engine before execution:

You can pass multiple facts when you run the engine by passing an object containing the fact: [`engine.run(facts, options)`](https://github.com/CacheControl/json-rules-engine/blob/master/docs/engine.md#enginerunobject-facts-object-options---promise-events).  Each key in the object is a fact.

__________________

If the question was about adding runtime fact, it's a little more complicated:

During an engine run, when using [`almanac.addRuntimeFact`](https://github.com/CacheControl/json-rules-engine/blob/master/docs/almanac.md#almanacaddruntimefactstring-factid-mixed-value) I don't believe you can do something quite as easy as above.  However, you could do something like:
```javascript
almanac.addRuntimeFact('runtimeFacts', {
  someFact: 1,
  anotherFact: 2
});
```
However, this would result in the rules needing to have a `fact` of `runtimeFacts` and a `path` of `.someFact` or `.anotherFact`.

Alternatively, if the addition of path is unattractive to you, you could define an object of facts and essentially loop though it using [Object.entries](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) or a similar lodash utility, adding facts along the way.

**Comment by manerohit388** [comment]
@MattCopenhaver  Thanks for quick response. Let me explain my scenario.
`let rule = {
	conditions: {
		all: [
			{
				any: [
					{
						fact: 'action',
						operator: 'equal',
						value: 'unk'
					},
					{
						fact: 'action',
						operator: 'equal',
						value: 'na'
					}
				]
			},
			{
				all:[
					{
						fact: 'status',
						operator: 'equal',
						value: 'active'
					}
				]
			}
		]
	},
	event: {
		type: 'in-progress',
		params: {
			message: "Order is in-progress"
		}
	},
	priority: 10,
	onSuccess: function (event) {
		console.log(event.params.message)
	},
	onFailure: function(event, almanac) {
		console.log("Rule not executed")
	}
}
engine.addRule(rule);`

For me fact is json object like this` {status: 'active', action: 'na'}`. I want to add multiple such facts like `{status: 'inactive', action: 'na'}`  , `{status: 'active', action: 'unk'}` Is this possible with json-rules-engine ? If yes then how to achieve this.

**Comment by MattCopenhaver** [comment]
I think there is a misunderstanding about what exactly a fact is in your example.  

If you want to add both of the following:
```javascript
{status: 'inactive', action: 'na'}
{status: 'active', action: 'unk'}
```
using ex. `status` as a fact would not work because you would be overwriting the value of `status` as you add subsequent facts.  Same for `action`.

I am assuming these are two distinct objects, which you could identify uniquely.  Depending on how you want this to work, I can think of two possible ways to accomplish this, based on the two possible understandings I have of your use case.

1.
Key these object uniquely and add that as the fact.
```javascript
engine.run({
  fact1: {status: 'active', action: 'na'},
  fact2: {status: 'active', action: 'unk'}
});
```
and your rules would need to change to something like this (notice `path`):
```javascript
{ fact: 'fact1', path: '.action', operator: 'equal', value: 'unk' }
```
I don't really think this is what your use case is, though.

2. 
Add a fact as an array, and use the 'contains' operator:
```javascript
engine.run({
  myFact: [
    {status: 'active', action: 'na'},
    {status: 'active', action: 'unk'}
  ]
});
```
Then I believe you would need to write a custom operator, similar to [contains](https://github.com/CacheControl/json-rules-engine/blob/master/docs/rules.md#array-operators), which checks for equality of nested values in an array of objects.

**Comment by manerohit388** [comment]
Your understanding is correct. I want to implement 2nd case. I tried to use custom operator like `contains`. Here is my updated rule:

`{
	conditions: {
		all: [
			{
				any:[
					{
						fact: "medications",
						operator: "contains",
						value: "unk"
					},
					{
						fact: "medications",
						operator: "contains",
						value: "na"
					}
				]
			},
			{
				all: [
					{
						fact: "medications",
						operator: "contains",
						value: "active"
					}
				]
			}
		]
	},
	event: {
		type: "in-progress",
		params: {
			message: "Order is in-progress"
		}
	},
	priority: 10
}`

I have added custom operator "contains" to the engine like this:

`engine.addOperator("contains", (factValue, jsonValue) => {
	if(!factValue.length)
		return false;

	for ( const item of factValue) {
		if ( item.hasOwnProperty("action") && item["action"] === jsonValue)
			return true;
		else if (item.hasOwnProperty("status") && item["status"] === jsonValue)
			return true;
		else
			false;
	}
});`

Now the issue is that, i am not able to figure out which facts are evaluated successfully against the rule. When i use `ruleResult` to obtain results i can see entire array is being returned. Is this the correct way to evaluate facts array ? Did I made any mistake in implementing the custom operator ? Could you please provide an example on how to evaluate facts array and return evaluated facts. Your help is appreciated.

**Comment by CacheControl** [comment]
The entire array is being returned in the RuleResult because that's the `fact`'s datastructure; this is working as intended. If you need to know which particular parts of the array passed the condition, then you may want to generate a rule for each individual element of the array. That way when the rule triggers 'success', you know exactly what object passed.
