### ISSUE TITLE
Engine operator "in" always returns true if we check the existence of empty object

### ISSUE THREAD

**Issue by pnguyen9** [CacheControl/json-rules-engine#158]
https://github.com/CacheControl/json-rules-engine/blob/master/src/engine-default-operators.js#L8

In Javascript, indexOf(myString) returns 0 if myString is an empty string. 

```
const myVariable = "hello";
myString.indexOf(""); // returns 0
```

However, if myVariable is an array converted into json and we check for the presence of an empty object (converted into an empty string in json), the "in" operator will still return true, despite the array not containing the empty object. 

```
const myArrayAsJson = "{['hello']}";
myArrayAsJson.indexOf("") > -1; // returns true
```

**Comment by CacheControl** [comment]
@pnguyen9 It sounds like you are checking whether a _string_ contains an empty value. That the string is serialized json is irrelevant; in javascript performing `indexOf('')` on any string will always return 0 rather than -1.

If you're trying to detect the present of something within an array, the fact should be added to the engine as a javascript object, not a string.
