### ISSUE TITLE
RuleResult does not serialize 

### ISSUE THREAD

**Issue by silesky** [CacheControl/json-rules-engine#172]
Related to: https://github.com/CacheControl/json-rules-engine/issues/47

I get the following response when attempting to to serialize a RuleResult (i.e. using express's `res.json(ruleResult)` method).
```
"{\"conditions\":{\"priority\":1,\"all\":[{\"priority\":1,\"any\":[{\"priority\":1,\"any\":[{\"operator\":\"in\",\"value\":[\"foo\",\"bar\",\"baz\"],\"fact\":\"productType\",\"factResult\":\"baz\",\"result\":true}...
```

As a workaround, I've done `JSON.parse(JSON.stringify(ruleResult));`

can we either: 
- have them serialize properly
- add a `.toJSON()` method?

**Comment by CacheControl** [comment]
I'm unable to reproduce this problem - perhaps this is no longer a problem due to rule-result now having a [toJSON() method](https://github.com/CacheControl/json-rules-engine/blob/master/src/rule-result.js#L18) defined?

```js
const stringified = JSON.stringify(ruleResult)
console.log(stringified)
// no double escaping:
// {"conditions":{"priority":1,"any":[{"operator":"greaterThanInclusive","value":21,"fact":"age","factResult":21,"result":true},{"operator":"equal","value":true,"fact":"qualified","factResult":false,"result":false}]},"event":{"type":"setDrinkingFlag","params":{"canOrderDrinks":true}},"priority":100,"result":true}
```

I checked the express source code and they're not doing anything fancy - just [JSON.stringify()](https://github.com/expressjs/express/blob/master/lib/response.js#L1123)

If anyone still has this problem please comment and we'll re-open. Thanks!
