### ISSUE TITLE
Seems like a failure should be returned but it is not. Ideas?

### ISSUE THREAD

**Issue by clearly** [CacheControl/json-rules-engine#174]
```
const { Engine } = require( 'json-rules-engine' );
const convert = require('xml-js');
const fs = require('fs');

const options = { ignoreComment: true, compact: true, spaces : 2, nativeType : true };

const rules = [
  {
    "event": {
      "type": "E00001"
    },
    "conditions": {
      "all": [
        {
          "fact": "NbOfTxs",
          "operator": "equal",
          "value": 1,
          "path": ".Document.FIToFICstmrCdtTrf.GrpHdr.NbOfTxs._text"
        }
      ]
    }
  }
];

const engineOptions = {
  allowUndefinedFacts: true
};

const xmlString = fs.readFileSync( './data/pacs.008.001.002.xml', 'utf8' );
const doc = convert.xml2js( xmlString, options );
let engine = new Engine( rules, engineOptions );

async function main() {
  
  console.log( doc.Document.FIToFICstmrCdtTrf.GrpHdr.NbOfTxs._text );
  const result = await engine.run( doc );
  console.log( JSON.stringify( result, null, 2 ) );
}

main();

/* OUTPUT
2
{
  "events": [],
  "almanac": {
    "factMap": {},
    "factResultsCache": {},
    "allowUndefinedFacts": true
  }
}
*/
```

**Comment by clearly** [comment]
So it looks like this behavior is "as designed". The use of "allowUndefinedFacts" prevents the use of a path. I must say, what am I missing as this seems like if I have to manually register every single fact as opposed to inspection of a large object tree I don't see much use in the lib.

**Comment by CacheControl** [comment]
@clearly You ought be able to use `allowUndefinedFacts` in concern with `path`. Of course, since the `path` refers to the fact, if the fact is undefined then there's nothing for the path to reference. I tried to run your example code, but because I don't have the `./data/pacs.008.001.002.xml`, I'm unable to reproduce the problem - if you provide a version that doesn't have a dependency I can help troubleshoot.
