### ISSUE TITLE
Failure Callback

### ISSUE THREAD

**Issue by alnguyen** [CacheControl/json-rules-engine#18]
Is there a way to determine, on `failure`, which rule/condition failed?

**Comment by CacheControl** [comment]
No, though there's a slight workaround - see #16.

**Comment by CacheControl** [comment]
I've just published **2.0.0-beta1** which contains this capability.  There's an [example](https://github.com/CacheControl/json-rules-engine/blob/7974907ba41a78a8ac6a195229ea04c28b8fd2de/examples/09-rule-results.js) in pr #35 and some docs [here](https://github.com/CacheControl/json-rules-engine/blob/7974907ba41a78a8ac6a195229ea04c28b8fd2de/docs/rules.md#rule-results) and [here](https://github.com/CacheControl/json-rules-engine/blob/7974907ba41a78a8ac6a195229ea04c28b8fd2de/docs/rules.md#events)

This a beta because I'm going to let it stew for a week or so to provide the various stakeholders an opportunity to give feedback.  Please let me know if you have any input.
