### ISSUE TITLE
stop other conditions if one succeeded

### ISSUE THREAD

**Issue by adham-suwan** [CacheControl/json-rules-engine#180]
When using "any" in rule conditions, is there any way to stop executing other conditions if one succeeded?

**Comment by pasblin** [comment]
may be yo could separate any conditions in diferent rules and add params to event like this:
```javascript
{
   "event":{
      "type":"mi-event",
      "params":{
         "stop":"...."
      }
   },
   "conditions":{
      "all":[
         {
            "fact":"prop",
            "operator":"equal",
            "value":true
         }
      ]
   }
}
```

and :
```javascript
engine.on('success', (event, almanac, ruleResult) => {
    if (event.params && Object.prototype.hasOwnProperty.call(event.params, 'stop')) {
        ........
        engine.stop()
    }
 })
```

**Comment by CacheControl** [comment]
@adham-suwan I assume you're referring to conditions containing dynamic facts, which trigger functions and have a promise interface. Since canceling promises isn't part of the promise specification, I don't think that's something json-rules-engine can do for you. Let me know if I'm misunderstanding or incorrectly assumed what your use case is.

**Comment by kodeine** [comment]
so if the rules are chained and we want to halt the next rule because the previous one was dependent on the next, since previous failed we cant move to next rule. In that case we need to halt/stop the engine.
