### ISSUE TITLE
Conditionally Execute Rules in a Tree Structure

### ISSUE THREAD

**Issue by MattCopenhaver** [CacheControl/json-rules-engine#208]
Hello again @CacheControl!

A recent feature I've been thinking about, that would be beneficial to my use case, is executing multiple rules in a tree structure.  The idea is that there are a set of conditions which, when evaluated to true, would indicate the need to execute a particular group of rules.

This would be enormously helpful to us to better organize my rules, but also to improve performance by not executing many of the rules.

Below is the logical model of how I think about the rules:

<img width="386" alt="Screen Shot 2020-05-06 at 10 45 36 AM" src="https://user-images.githubusercontent.com/12800786/81191193-c0210300-8f86-11ea-86dd-c40c37542dd5.png">

Now, I could easily implement this a 7 rules that all execute each time, with the conditions added to each rule.  All 7 rules would run and all 7 rules would have more conditions to evaluate.  What I'd like to happen, is for the conditions in the diamond to only execute once, then either rules 1-3 or rules 4-7 to execute.

I'd also add that this should be nestable, as in this picture:

<img width="461" alt="Screen Shot 2020-05-06 at 10 54 07 AM" src="https://user-images.githubusercontent.com/12800786/81192204-ee531280-8f87-11ea-89f8-c83a3240c4dd.png">

Is this a capability/feature you feel should be added to the engine, or is this something you feel should be done outside of the engine?  I would be happy to do a PR to add the capability if you think it would be valuable, or have any guidance on how to add it.

**Comment by naveen-shetty** [comment]
Hi @CacheControl, Did you get a chance to look at this request? Would appreciate your thoughts here.

**Comment by ozanerturk** [comment]
For Organization:
You are grouping rules but each of these groups has the same event after the evaluation?
Normally each rule should be designed for a particular event that will be processed after evaluation.
I mean the important thing is events, not the grouping rules. 
If you have identical events for some different rules maybe that is because they are not separated rules. 

For performance, 
Ordering the facts with respect to their importance probably solves this problem. Because boolean evaluation will not proceed after first failure occurred

**Comment by MattCopenhaver** [comment]
@ozanerturk Each rule would have a different event.  

Yes, it would be possible to meet the same logical need by implementing the segmentation conditions in the first condition of each rule (within an `all`).  

However, the example above is a relatively simple one, where there are only 1 or two segmentation conditions.  As the number of segmentation conditions grows, the number of rules grows exponentially and the number of conditions within each rule grows linearly.

**Comment by ozanerturk** [comment]
Hmm. isn't that seems like routing for you too? 
What if we create a rule that has an event executing related rules?

**Comment by kodeine** [comment]
is this lib still maintained?

**Comment by CacheControl** [comment]
Hey @MattCopenhaver sorry for the long delayed response, I had a busy 2020 and am trying to catch up. Thanks for taking the time to write this up with some nice diagrams.

I like the idea in theory and it sounds like something many users might run into. In terms of modeling the tree structure, I'm concerned it could get a bit "meta" - "a rules engine deciding which rules engines to run", if you will. I'm wondering if the same thing can be achieved (albeit less elegantly) with some imaginative use of fact priorities. I'm thinking each group of rules could all contain a `group` condition that dictates which set of rules it belongs to, e.g.:

```js
{
      fact: 'group',
      operator: 'equal',
      value: 1,
}

engine.addFact('group', 1, { priority: 100 }) // evaluate conditions using this fact before all other conditions
```

This is a 'flat' solution vs the tree version you're proposing, in that every rule would require this group condition. I'll concede that unlike the tree approach, the engine would have to evaluate every rule - it's not quite as efficient. However I'd argue that the cost of this extra evaluation will be trivial since it's a simple scalar check which should allow the engine to run through the extra rules extremely quickly.

What do you think? Are there other drawbacks to the flat approach I'm not seeing (or maybe there's a reason why it won't work 😆 )?
