### ISSUE TITLE
Provision of a function/method while defining rules

### ISSUE THREAD

**Issue by arsalans** [CacheControl/json-rules-engine#23]
@CacheControl So consider we need to have a rule which needs to check whether the volume of an item is bigger than say 100 and it takes three arguments:

1. Length
2. Breadth
3. Height

How can we write this kind of rule that needs to multiply the three arguments to check the condition?

**Comment by slmmm** [comment]
In the past, I've used Custom Facts to build functions that do this.  I used the documentation as reference.

**Comment by arsalans** [comment]
@slmmm Hi, would you be able to point out at the documentation about this? Any example would come in really handy as well.

**Comment by slmmm** [comment]
I'm sure @CacheControl  has a more elegant implementation :-), but here's a stab at it.

In my project I set up a folder of custom fact modules (which are just js functions).  So for your case, could have a module file containing (can require it into any module that'll reference the fact):
module.exports = {
  name: 'volume',
  fact: function (params, almanac) {
    let length = 0;
    let breadth = 0;
    let height = 0;
    return almanac.factValue(length)
      .then(function (response) {
        length = response;
        return almanac.factValue(breadth);
      })
      .then((response) => {
        breadth = response;
        return almanac.factValue(height);
      })
      .then((response) => {
        height = response;

        return length * breadth * height;
      })
      .catch(function () {
        return 0;
      });
  }
};

As well, I had a Rules folder where I created a rule file for each set of rule conditions.  In this scenario would have a file that contained just the json (so that we could read/save to file for end-user maintenance):
  {
    "priority": 50,
    "event": {
      "type": "check-dimensions",
      "params": {
        "message": "The volume is not big enough"
      }
    },
    "conditions": {
      "all": [
        {
          "fact": "volume",
          "operator": "lessThan",
          "value": 100
        }
      ]
    }
  }

Then would load the Fact and Rule into engine.
engine.
      let fact = require("../Facts/volumeFact.js");
      engine.addFact(fact.name, fact.fact);

<< ... elsewhere read in json file containing 'rule' ...>>
          let engineRule = new Rule({
            conditions: rule.conditions,
            event: rule.event,
            priority: rule.priority
          });
          engine.addRule(engineRule);

Then can run the engine:
      engine.run(myObjectToCheck).then(...).catch(....);


I didn't test any of the above - just wanted to give an idea of approach.

When I set about using the json-rules-engine in this way, I used this example as a jumping point.
https://github.com/cachecontrol/json-rules-engine/blob/master/examples/03-dynamic-facts.js

**Comment by arsalans** [comment]
Thank you very much @slmmm.

@CacheControl is that the best way to go forward?

**Comment by CacheControl** [comment]
@arsalans yep, dynamic facts are the way to go.  Thanks @slmmm for putting together an example.

**Comment by arsalans** [comment]
@slmmm Since I am new to this, can you tell me why can't I write my "volume' fact like this:

module.exports = {
  name: 'volume',
  fact: function (params, almanac) {
    return length * breadth * height;
  }
};

**Comment by slmmm** [comment]
@arsalans - in my past use of the library, the only way to get the values of properties on your object that you're checking is to request one by one using the almanac store that has the async factValue() method.  Instead of using the tree of promises in synchronous order, I believe you could set it up to use parallel async calls on almanac.factValue(myPropertyNameHere) but be careful with that strategy if any of your property values are also themselves calculated dynamic facts (race conditions).

**Comment by arsalans** [comment]
@slmmm I just got a chance to work on this problem and your example works great so thank you again for this.

@CacheControl So the example @slmmm gave works great, however I was thinking for simplicity, what are the chances if we are able to write a rule like this (I do understand that it is going to be an enhancement - nice to have pretty much): 

```
let facts = {
    length: 10,
    breadth: 2,
    height: 3
  };
```

```
  let volumeRule = new Rule({
    conditions: {
      all: [{
        fact: length * breadth * height,
        operator: 'greaterThanInclusive',
        value: 100
      }]
    },
    event: {  // define the event to fire when the conditions evaluate truthy
      type: 'fouledOut',
      params: {
        message: 'Player has fouled out!'
      }
    }
    ,
    priority: 100
  });
```

So in essence, the condition field of the rule can take an expression containing facts.

**Comment by CacheControl** [comment]
If you know `length`, `breadth`, `height` ahead of time, you can simply do the calculation outside the engine, and pass it in as a constant:

```
let volume = length * breadth * height
engine.run({ volume })
```

The advantage of doing the `factValue` approach is that the calculation is only done on-demand (i.e. it is run when the engine counters a rule that includes this fact), and it also allows the engine to calculate the value a single time if it encounters `volume` across multiple rules (it caches the value after the first calculation).  However, if you happen to be in a situation the previous 2 advantages don't get you much, there's no reason not to go for the simpler approach of passing `volume` to `run()`.

**Comment by arsalans** [comment]
@CacheControl you are right we can, and we will do either that or use dynamic facts. It still remains nice to have to not worry about it and let the rule handle it though.

**Comment by CacheControl** [comment]
Cool, I'll close this for now.  Feel free to re-open if you run into any issues
