### ISSUE TITLE
 CommonJS or AMD dependencies optimization bailouts.

### ISSUE THREAD

**Issue by toamitc** [CacheControl/json-rules-engine#234]
With Angular 10, CLI shows warning for  Json-rule-engine  for optimization bailout. Is there any planned fix for this?
Warning from console:
'json-rules-engine'  CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by CacheControl** [comment]
@toamitc Thanks for the links. Based on my understanding of what Angular is saying, the "fix" for this would be to change the project to use ESModules, and get rid of CommonJS `require`s. I'm definitely game to do that at some point, however since this is an isomorphic package, we need to be sensitive to the node.js community. Node.js is still a ways away from fully enabling ESModule support - I think the last I heard it should come sometime in late 2021.

I'm going to close the issue for now, since I don't see a way forward given current node.js support. Please let me know if there's another option for what can do in the meantime!
