### ISSUE TITLE
Ability to get dynamic fact value on success

### ISSUE THREAD

**Issue by ThanosDi** [CacheControl/json-rules-engine#239]
Is there a way to get all facts value whether it's dynamic or constant on success callback?
For example:
```
	engine.addFact('time', new Date());
	engine.addFact(
		'timeSpend',
		function (__parameters, almanac) {
			return almanac.factValue('time').then(time => {
				return Number.parseInt((new Date() - time) / 1000, 10);
			});
		},
		{cache: false}
	);
       engine.on('success', (event, __engine) => {
		const facts = Array.from(__engine.factMap, ([name, {value}]) => ({
			name,
			value
		}));
                // timeSpend value is not defined.
       );
```

**Comment by CacheControl** [comment]
`factMap` is an internal data structure - I'd recommend using [almanac.factValue()](https://github.com/CacheControl/json-rules-engine/blob/master/docs/almanac.md#almanacfactvaluefact-fact-object-params-string-path---promise) in the `on('success')` callback - [see example](https://github.com/CacheControl/json-rules-engine/blob/master/examples/09-rule-results.js#L63).

It's not possible to get an array of all fact values without calling `almanac.factValue()`, because the fact value depends upon both the `params` and the `path` passed to that method.
