### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by maheshcv** [CacheControl/json-rules-engine#33]
I get this error "SyntaxErrorL: Unexpected token import" in node.js v7.7.4 and v6.10.1 while running. How do you run this? Would be useful to add this information the readme

**Comment by codebreach** [comment]
I believe you have to use `babel` and then run using `babel-node` instead of `node`

**Comment by CacheControl** [comment]
@maheshcv Sorry you're having trouble.  `json-rules-engine` is compatible with node 4+; you should not require babel or any other special tools.  Can you provide the stack trace for your error?

**Comment by codebreach** [comment]
As far as running the module itself (and not requiring it from your own module), you need to use Babel.

This is because the code has `import * from 'blah'` statements which are not supported in Node up to v6.
See http://stackoverflow.com/questions/36901147/es2015-import-not-working-in-node-v6-0-0-with-with-harmony-modules-option

However if you are simply requiring it from some other project then it should work and a stack trace would really help.

**Comment by CacheControl** [comment]
@maheshcv Were you able to figure this out?  Is there anything we can assist with?

**Comment by CacheControl** [comment]
Sounds like things have been resolved; closing this out.
