### ISSUE TITLE
Want to get in contact

### ISSUE THREAD

**Issue by dlombardi** [CacheControl/json-rules-engine#49]
Hey Cache,

Can't find any other way to DM you so I'm logging an issue ¯\_(ツ)_/¯. I'm building my own version of a json-rules-engine (https://github.com/dlombardi/rules_engine) that's very much inspired by yours. It's mainly for an educational purpose but I'm hoping to find a niche for it through dynamic forms based on rules. I was hoping to pick your brain a bit on the design philosophy behind the json-rules-engine especially related to the almanac, but also other things.  Sorry again to do this through an issue.  If theres anytime we can have a convo It would certainly help me grow as a developer and would be very much appreciated.  I've learned a lot by looking at your code already.

**Comment by CacheControl** [comment]
Hi @dlombardi 

Guess I should actually put my email on my github profile :)  You can contact me at `cache.hamm@gmail.com`

**Comment by alank64** [comment]
Hi @dlombardi  Define the "niche", because from my understanding is that json-rules-engine is purely and efficiently a rules processing engine, your forms would feed facts into it and applied to rule definitions. I think what you really want to build is a module that requires json-rules-engine and thus feeds form facts into it.
