### ISSUE TITLE
Optional condition value

### ISSUE THREAD

**Issue by jgoux** [CacheControl/json-rules-engine#50]
Hello,

I have some operators that doesn't require a condition value (EXISTS, NOT EXISTS)

Could it be made optional ? I can pass `value: null` but would be better to just not pass it at all. 👍

**Comment by alank64** [comment]
I haven't tried it yet, just building the base right now for json-rules-engine, but creating your own conditions see

https://github.com/CacheControl/json-rules-engine/blob/master/docs/engine.md#engineaddoperatorstring-operatorname-function-evaluatefuncfactvalue-jsonvalue

Does that not help or give you that option?

**Comment by jgoux** [comment]
This is what I actually use to define my `exists` and `not exists` operators.
The thing is I don't need the `jsonValue` part, because the operator is opering only on the `factValue`.
It's just something like : `factValue => factValue !== undefined`.

So the logic would be to not have to specify a value key in the condition, but if I omit it, it raises an error about it.

**Comment by CacheControl** [comment]
@jgoux Sorry for the delayed response; I've been busy.

I see your point, and I think it's a good one.  There's a couple considerations we'd need to think about and investigate before this change could be implemented:

- Developer friendliness; if a `value` prop is not provided, is that most likely due to programmer error (a bug)?  If so, does value of allowing undefined properties outweight the cost of allowing devs to potentially shoot themselves in the foot?
- json serialization does not include undefined properties.  does that matter / do we care?
- due diligence around the code itself to ensure things won't break by allowing this.

For now your best bet is to simply add those explicit `null`s, which it sounds like you've already done.

**Comment by alank64** [comment]
In effect you only need an "exists" operator, if I understood correctly.

maybe this could be published in the documentation in the future:

```
engine.addOperator('isEmptyString', (fact, value) => {
    if (fact === undefined){
      return !value;
    } else if (fact.length < 1){
      return value;
    } else {
      return !value;
    }
  });
```
Note there is probably a cleaner way to code this, just expanded for this explanation and consider arrays, maybe of objects etc! ;)

But the idea here is that given...

```
conditions: {
    all: [{
      fact: 'user',
      operator: 'isEmptyString',
      value: false,   // or true if string must be null or undefined
      path: 'something.email'
    }]
  },
```

Returns false or true given the operator and value. In addition I agree about value being optional but if this was enabled we would have to code two operators for handling this rather than one that handles both conditions via a true/false "value" property.

Maybe if you provide the use case code it might better help me understand. Like rules and conditions.

**Comment by CacheControl** [comment]
version **5.3.0** ([changelog](https://github.com/CacheControl/json-rules-engine/blob/master/CHANGELOG.md#530--2020-12-02)) adds the support for `undefined` fact values. This effectively solves this issue, as you may now craft conditions which check for `undefined`:

```js
{
      fact: 'my-fact',
      operator: 'equal',
      value: undefined,
}
```
