### ISSUE TITLE
Question, can I compose rules? Do I need multiple engines

### ISSUE THREAD

**Issue by DayBr3ak** [CacheControl/json-rules-engine#87]
I want to compose my rules to avoid duplicated rules and give my users flexibility

what I'm doing right now in a naive way is something like
```js
if value in jsonValue
  run engine with rules for this value
  if no events run engine with fallback rules
else run engine with fallback rules
```

it looks like this 

```js
  let success = false
  let result
  if (ctx.value) {
    const events = await engine1.run(ctx)
    success = !!events.length
    result = success ? events[0].params.result: undefined
  }

  if (!success) {
    const events = await engine2.run(ctx)
    success = !!events.length
    result = success ? events[0].params.result : undefined
  }
  return result
```

There's a lot of repetition code with fallback rules and regular rules. Any suggestions?

**Comment by CacheControl** [comment]
Hi @DayBr3ak 

It's hard to answer this without more context around what a fallback rule is vs a regular rule.  But if I understand the jist of the challenge, it's that there's two different categories of rules, and certain rules are shared between each category.  You're wondering if there's a way to DRY up the rules, so that they're not duplicated across each category.

If you're able to know which rules common are common up front, then you could categorize them accordingly into an array, and load them into both engines (there is nothing preventing a rule from being used in many different engines).
