### ISSUE TITLE
Possibility to use variable as value in conditions?

### ISSUE THREAD

**Issue by MRTNPRSN** [CacheControl/json-rules-engine#89]
Hi there,
thanks for your work, I'am just wondering if it's possible to use dynamic variables for the values of conditions? What if my conditions need to evolve each time I run the engine? 

regards

**Comment by CacheControl** [comment]
@MRTNPRSN you have 2 options, depending on your situation.

- If the condition values are constant with each run, simply generate the rules using code instead of reading them from static json, and set the value of each condition.

- If the condition values change throughout the run of the engine, you'll want to look at the [fact-comparison](https://github.com/CacheControl/json-rules-engine/blob/master/examples/08-fact-comparison.js) example.  This feature allows you to use a fact as the 'value' property of a condition, which can be combined with a [dynamic fact](https://github.com/CacheControl/json-rules-engine/blob/master/examples/03-dynamic-facts.js) to allow the values to change as the engine runs.
