### ISSUE TITLE
Ability to include fact value in event

### ISSUE THREAD

**Issue by jdalydt** [CacheControl/json-rules-engine#97]
We are trying to do the following:
1) Use Rules to assign scores to various Facts
2) Sum those scores together in a lower priority rule
3) Use a final Rule to grade the final score (e.g. low, medium, high).

The output of `Engine.run()` is an array of Events, and we would like these events to include parameters containing the outputs of 1), 2) and 3). However, including the output of 2) in an Event is proving problematic as the Event parameters have to be defined statically - how can we get the summed score into the Event?

We'd like to do something like the below (as part of the rule definition):

```javascript
"event": {
    "type": "summedScore",
            "params": {
                "value": $myFact.value
            }
}
```

Is there a way to do this, or is there an alternative approach we could take? We would prefer not to use the almanac as we don't have access to it from the output of `Engine.run()`.

**Comment by CacheControl** [comment]
@jdalydt 🤔 It sounds like the fundamental challenge here is around aggregating rule results and feeding the result into a new rule, all within the same engine `run()`.  This is tricky because you need your aggregation logic to run after `1.`, but before `.3`...and although you may be able to use priorities to cajole the right order, it feels complicated to me; I suspect we're trying to do too much in a single engine `run()`, and even if we were to get things to work, you might not be happy with the amount of complicity it would add.

Can we simplify by moving the aggregation complexity outside the engine?  For example, could we could break those steps out into 2 engines - one with rules for scoring the facts, some external logic to sum those results, and then a second engine to grade the final score?

**Comment by jdalydt** [comment]
@CacheControl That seems like a reasonable solution. 

Another solution we have come up with is to add a dynamic Fact to the engine that calculates the sum of the sub-scores as part of step 3 - the downside of this is that the summed score cannot be emitted as part of the event (since it is not a static thing) and we therefore have to do the summing logic again when processing the events - which is obviously very cheap, but not particularly elegant.

However, I suspect the solution you suggested is the cleanest from the point of view of the rules engine side. Do you think there are performance implications as a result of the overhead of two separate engines?

**Comment by CacheControl** [comment]
@jdalydt Great, glad to hear you've got some options, and the fact that it's not the most elegant is duly noted.

There shouldn't be overhead in terms of extra Engine instances - it's really just a shell for holding a `rules` array.  Please do feel free to benchmark rather than taking my word for it though, and if you see any non-trivial overhead I'd love to know.
