### ISSUE TITLE
json path

### ISSUE THREAD

**Issue by colps** [CacheControl/json-rules-engine#99]
Hi, I am writing a custom operator to compare two arrays. I have a requirement where I want to select an array of strings from an array of objects in my fact (like json path `$.phoneNumbers[*].type`).  

```
{
  "firstName": "John",
  "lastName" : "doe",
  "age"      : 26,
  "address"  : {
    "streetAddress": "naist street",
    "city"         : "Nara",
    "postalCode"   : "630-0192"
  },
  "phoneNumbers": [
    {
      "type"  : "iPhone",
      "number": "0123-4567-8888"
    },
    {
      "type"  : "home",
      "number": "0123-4567-8910"
    }
  ]
}
```
Expected output : `['iPhone', 'home']` 
My understanding is that selectn does not support this and I do not want to use dynamic facts to do this, since I want to keep the rules configurable. Is there a work around we can use? 
One solution is to define json path in a fact as shown below and use https://www.npmjs.com/package/jsonpath to evaluate.

```
{
   fact: 'person',
   operator: 'containsAnyOf',
   value: ['home', 'office'],
   jsonPath: '.phoneNumbers[*].type'
}
```
Thanks

**Comment by CacheControl** [comment]
Hmmm sounds like you've done your research @colps. I'm now a little annoyed with myself for choosing `selectn` over `jsonpath`, which clearly covers more use cases.  Aside from the dynamic fact option you already explored, I can't think of any alternatives.

From your example it looks like you're planning on using a `containsAnyOf ` custom operator that can perform the json path invocation - if so,  I'm curious how were you planning on retrieving the `jsonPath` property?

**Comment by colps** [comment]
@CacheControl The operator won't be evaluating the json path. The ideal solution will be to make changes in the engine to support `jsonPath`. I have been going through the engine's source code and I think, changes will be required in `condition.js` and `almanac.js` (at the very least). 
`jsonPath` and `path` properties can be kept mutually exclusive. This way the engine can support `selectn` and `jsonPath`.

Finally, a really ugly way to do this will be to put the jsonPath in the rule value as shown below.
```
{
	 fact: 'person',
	 operator: 'containsAnyOf',
	 value: {
	       value: ['home', 'office'],
	       jsonPath: '.phoneNumbers[*].type'
	 },   
}
```
I have not tried this but this way the jsonPath should be available in the operator callback as part of the `jsonValue` argument. I do not plan to use this solution though. Let me know what you think.

Thanks

**Comment by colps** [comment]
Hi @CacheControl , Did you get a chance to go through my reply? I would like to know how difficult will it be to add support for jsonPath in the tool, if we were to fork and make the changes ourselves.
Thanks.

**Comment by CacheControl** [comment]
@colps if you follow the changes made to to support `path`, I'd imagine adding `jsonPath` wouldn't be difficult at all.  I'm conflicted as to whether I'd like to see this in `json-rules-engine` itself, as this is the first evidence of this need and it would add a sizeable dependency (we have many front end users of this library).

I think for now your best approach may be to fork as you suggest, and I'll pull the changes into the core library if or when demand warrants it.  `json-rules-engine` has been very stable over the last year and required few updates, so I doubt if we'd see much divergence in the codebases.

**Comment by dcworldwide** [comment]
Just so that it is considered....jsonpath would add a fair bit of package weight 

<img width="1423" alt="Screen Shot 2019-08-09 at 08 42 46" src="https://user-images.githubusercontent.com/4898751/62742401-c6c72c00-ba81-11e9-8a77-7e902347b0ae.png">

**Comment by CacheControl** [comment]
Agreed. The massive size of `jsonpath` continues to be my main reluctance to implement this feature. I've been hoping to have a stroke of insight into how this feature might work as a plugin / peer dependency, but it hasn't happened yet.

**Comment by phstc** [comment]
What would be the recommended approach for an operator to check a value from a list?

For my use-case, I have a list of products and I want to rule out products with a given `productId`.

```json
{
  "items": [
    { "productId": 1 },
    { "productId": 2 },
    { "productId": 3 }
  ] 
}
```

I ended up creating a custom and very specific operator `doesNotContainProductId`: 

```typescript
Operators.push(
  new Operator("doesNotContainProductId", (items: Item[], ids: number[]) => {
    if (items === undefined) return true;

    for (const item of items) {
      if (ids.indexOf(item.productId) !== -1) return false;
    }
    return true;
  })
);
```

But I would love a generic option  `doesNotContain` setting `productId` as a `path`. 

It seems  that in  order to that the, [this](https://github.com/CacheControl/json-rules-engine/blob/1e0adf7eb8e3f137c98a15e8e8bc862560b2ed96/src/almanac.js#L111) could check if `factValue` is an Array, if so, return the ` map`  of the `path`. 

WDYT?

**Comment by CacheControl** [comment]
@phstc Solving for the particular data structure you posted is likely do-able (the code change you suggested might work). The tricky part I think is solving this in a way that will support everyone else's data structures as well. Although the most common case represented in this thread is an array of objects, there's no limit to the ways a user may choose to structure their data.

I'm a bit short on time these days, but ultimately I'd like to solve this in a comprehensive way.

**Comment by CacheControl** [comment]
Hi all,

just wanted to give a heads up that I'm actively working on this feature, in case anyone wanted to provide some early feedback on my plan of attack.

After surveying the options, it's clear that `selectn` syntax is fundamentally unable to express the full breadth of object traversal use cases desired by users. As such, it's in the best long term interest of this library to move forward with [json-path](https://goessner.net/articles/JsonPath/) as the primary supported syntax of the `path` feature (this is, after all,  a _json_ based library).

### deprecated support for selectn
I'm planning to deprecate support for `selectn` path syntax. If you want to continue using that format, you will have to install `selectn` as a direct dependency of your application, and json-rules-engine will detect its presence, path syntax, and use it to parse relevant condition paths. **This will be a breaking change because of the new requirement of adding `selectn` as a direct dependency**, but it won't force anyone to convert all their rules before upgrading to v5. In fact, you can technically continue to use the `selectn` syntax for old rules, and express json-path for new ones.

By removing `selectn` as a dependency, we'll save ~20% of the overall package size of json-rules-engine, and making the addition of `jsonpath-plus` fairly negligible (see below).

### which json-path library to use?

As discussed above, there was initial concern around having `jsonpath` as a dependency. For this reason, I'm planning to use [jsonpath-plus](https://github.com/s3u/JSONPath) instead. This library checks several important boxes:

- [x] Only 4kb gzipped. After removing the 2.4kb of space required by selectn, this means **we'll be providing the flexibility offered by the json-path specification at the bargain price of 1.6kb**
- [x] Runs in browser
- [x] Supports the json path syntax, plus some additional features for expressing more challenging cases (these non-specification features may be used optionally, of course)
- [x] Zero dependencies
- [x] [Very strong performance](https://github.com/andykais/json-querying-performance-testing) relative to competitors
